APPLICATION=shell

BOARD ?= iotlab-m3

RIOTBASE ?= /home/cerino/RIOT

DRIVER ?= lps331ap

USEMODULE += $(DRIVER)
USEMODULE += xtimer
# Add also the shell, some shell commands
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

include $(RIOTBASE)/Makefile.include


 

